FROM node:16-alpine

RUN apk update && apk add nginx bash make
COPY ./docker/nginx/proxy.conf /etc/nginx/proxy.conf
COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/default.conf /etc/nginx/sites-enabled/default

RUN chmod 777 -R /usr/local
RUN chmod 777 -R /var/
RUN mkdir -p /run/nginx && chown node:node /run/nginx
RUN su node -c "npm install -g pm2"

ARG NEXT_PUBLIC_SERVER_URL

ENV NEXT_PUBLIC_SERVER_URL ${NEXT_PUBLIC_SERVER_URL}
ENV PATH "/usr/local/bin:$PATH"

# Move the utility, client, and server files
WORKDIR /home/node
COPY ./docker/entrypoint.sh .
COPY ./client ./client
COPY ./server ./server
RUN chown node:node . -R

# Use the node user
USER node

# Build the server and add it to pm2
WORKDIR /home/node/server
RUN yarn --immutable --immutable-cache
RUN make -B db_seed
RUN make -B build

# Build the client and add it to pm2
WORKDIR /home/node/client
RUN yarn --immutable --immutable-cache
RUN yarn build

WORKDIR /home/node

CMD ["/home/node/entrypoint.sh"]
